languageCode = 'en-us'
title = 'blog@falon.dev'
theme = "terminal"

[params]
readMore = "Read more"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[languages]
  [languages.en]
    languageName = "English"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "portfolio"
        name = "Portfolio"
        url = "/portfolio"

